# -*- coding: utf-8 -*-
"""13. SLM as an Agent (LangChain + Pydantic)"""

!pip install -q langchain langgraph pydantic

from pydantic import BaseModel, Field
from typing import Optional

class MathAgentState(BaseModel):
    question: str
    plan: Optional[str] = None
    code: Optional[str] = None
    execution_result: Optional[str] = None
    final_answer: Optional[str] = None
    error: Optional[str] = None

def generate_response(model, tokenizer, prompt: str, max_new_tokens: int = 300) -> str:
    messages = [{"role": "user", "content": prompt}]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to("cuda")

    outputs = model.generate(
        input_ids=inputs,
        max_new_tokens=max_new_tokens,
        use_cache=False,
        temperature=0.7,
        top_p=0.9,
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    response = tokenizer.decode(generated_tokens, skip_special_tokens=True)
    return response.strip()

import re

def extract_section(text: str, header: str) -> str:
    pattern = rf"{header}:\s*(.*?)(?=\n[A-Z][A-Za-z ]*:\s|$)"
    match = re.search(pattern, text, re.DOTALL)
    return match.group(1).strip() if match else ""

def extract_code_block(text: str) -> str:
    # Regex to find a markdown code block for python
    # It looks for ```python then captures everything until ```
    patterns = [
        r"```python\s*(.*?)```",
        r"```py\s*(.*?)```",
        r"```\s*(.*?)```",
    ]
    for p in patterns:
      match = re.search(p, text, re.DOTALL | re.IGNORECASE)
      if match:
        return match.group(1).strip()

    return ""

def plan_and_code_node(state: MathAgentState) -> MathAgentState:
    prompt = f"""
You are a helpful math tutor for high school students.

Solve the following problem by producing:
Plan:
- short step-by-step reasoning

Code:
```python
- valid Python code that computes the answer
- print only the final numeric result

Question:
{state.question}
"""

    raw = generate_response(model, tokenizer, prompt)

    plan = extract_section(raw, "Plan")
    code = extract_code_block(raw) # Use the new function to extract code block

    if not code:
        return state.model_copy(update={
            "plan": plan or raw,
            "error": "No code generated by model."
        })

    if not plan:
      plan = "No explicit plan generated."

    return state.model_copy(update={
        "plan": plan,
        "code": code,
    })

import io
import contextlib

def python_execute(code: str) -> str:
    buffer = io.StringIO()
    local_vars = {}

    try:
        with contextlib.redirect_stdout(buffer):
            exec(code, {}, local_vars)
        output = buffer.getvalue().strip()
        return output if output else "Code ran successfully but produced no printed output."
    except Exception as e:
        return f"ExecutionError: {str(e)}"

def execute_code_node(state: MathAgentState) -> MathAgentState:
    if not state.code:
        return state.model_copy(update={"error": "No code available to execute."})

    result = python_execute(state.code)

    return state.model_copy(update={
        "execution_result": result
    })

def final_answer_node(state: MathAgentState) -> MathAgentState:
    if state.error:
        prompt = f"""
You are a math tutor for high school students.

The earlier attempt had this issue:
{state.error}

Question:
{state.question}

Give a short, student-friendly answer anyway.
"""
    else:
        prompt = f"""
You are a math tutor for high school students.

Use the reasoning and execution result below to answer clearly.

Question:
{state.question}

Plan:
{state.plan}

Execution result:
{state.execution_result}

Write a concise, student-friendly final answer.
"""

    final = generate_response(model, tokenizer, prompt)

    return state.model_copy(update={
        "final_answer": final
    })

from langgraph.graph import StateGraph, END

graph_builder = StateGraph(MathAgentState)

graph_builder.add_node("plan_and_code", plan_and_code_node)
graph_builder.add_node("execute_code", execute_code_node)
graph_builder.add_node("final_answer", final_answer_node)

graph_builder.set_entry_point("plan_and_code")
graph_builder.add_edge("plan_and_code", "execute_code")
graph_builder.add_edge("execute_code", "final_answer")
graph_builder.add_edge("final_answer", END)

math_agent = graph_builder.compile()

initial_state = MathAgentState(
    question="Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?"
)

result = math_agent.invoke(initial_state)

print("PLAN:\n", result['plan'])
print("\nCODE:\n", result['code'])
print("\nEXECUTION RESULT:\n", result['execution_result'])
print("\nFINAL ANSWER:\n", result['final_answer'])